//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firebase.Editor {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocRef {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocRef() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firebase.Editor.DocRef", typeof(DocRef).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Measure user activity and engagement with free, easy, and unlimited analytics..
        /// </summary>
        internal static string AnalyticsDescription {
            get {
                return ResourceManager.GetString("AnalyticsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log an Analytics event.
        /// </summary>
        internal static string AnalyticsGuideSummary {
            get {
                return ResourceManager.GetString("AnalyticsGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string AnalyticsName {
            get {
                return ResourceManager.GetString("AnalyticsName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        internal static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready to use Firebase on Android..
        /// </summary>
        internal static string AndroidConnected {
            get {
                return ResourceManager.GetString("AndroidConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To connect Firebase for Android, add the google-services.json from Firebase to your Assets..
        /// </summary>
        internal static string AndroidDisconnected {
            get {
                return ResourceManager.GetString("AndroidDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to set Minimum Target Android SDK level to {0}, this may be because
        ///you have an older version of the Android SDK installed on your machine.
        ///Try upgrading your Android SDK and setting the Android SDK level to {0} again..
        /// </summary>
        internal static string AndroidMinSdkVersionSetFailure {
            get {
                return ResourceManager.GetString("AndroidMinSdkVersionSetFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Android SDK Version?.
        /// </summary>
        internal static string AndroidSdkVersionChange {
            get {
                return ResourceManager.GetString("AndroidSdkVersionChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimum Target Android SDK needs to be set to level 14 or above.
        ///
        ///Change the Android SDK version to at least &quot;API level 14&quot; in:
        ///Build Settings -&gt; Player Settings -&gt; Other Settings -&gt; Identification -&gt; Minimum API Level
        ///.
        /// </summary>
        internal static string AndroidSdkVersionMismatch {
            get {
                return ResourceManager.GetString("AndroidSdkVersionMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect Minimum Android Version..
        /// </summary>
        internal static string AndroidSdkVersionMismatchSummary {
            get {
                return ResourceManager.GetString("AndroidSdkVersionMismatchSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in and manage users with ease, accepting emails, Google Sign-In, Facebook and other login providers..
        /// </summary>
        internal static string AuthDescription {
            get {
                return ResourceManager.GetString("AuthDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email and password authentication.
        /// </summary>
        internal static string AuthGuideSummary {
            get {
                return ResourceManager.GetString("AuthGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string AuthName {
            get {
                return ResourceManager.GetString("AuthName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deliver and receive messages and notifications reliably across cloud and device..
        /// </summary>
        internal static string CloudMessagingDescription {
            get {
                return ResourceManager.GetString("CloudMessagingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Cloud Messaging.
        /// </summary>
        internal static string CloudMessagingGuideSummary {
            get {
                return ResourceManager.GetString("CloudMessagingGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloud Messaging.
        /// </summary>
        internal static string CloudMessagingName {
            get {
                return ResourceManager.GetString("CloudMessagingName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not copy file {0} to {1}..
        /// </summary>
        internal static string CouldNotCopyFile {
            get {
                return ResourceManager.GetString("CouldNotCopyFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not locate google-services.json or GoogleService-Info.plist files..
        /// </summary>
        internal static string CouldNotFindPlistOrJson {
            get {
                return ResourceManager.GetString("CouldNotFindPlistOrJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not parse the file {0} as a plist file. Redownload from the firebase console?.
        /// </summary>
        internal static string CouldNotTranslatePlist {
            get {
                return ResourceManager.GetString("CouldNotTranslatePlist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get clear, actionable insight into app issues with this powerful crash reporting solution..
        /// </summary>
        internal static string CrashlyticsDescription {
            get {
                return ResourceManager.GetString("CrashlyticsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Crashlytics.
        /// </summary>
        internal static string CrashlyticsGuideSummary {
            get {
                return ResourceManager.GetString("CrashlyticsGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crashlytics.
        /// </summary>
        internal static string CrashlyticsName {
            get {
                return ResourceManager.GetString("CrashlyticsName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store and sync data across all clients in realtime..
        /// </summary>
        internal static string DatabaseDescription {
            get {
                return ResourceManager.GetString("DatabaseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Realtime Database.
        /// </summary>
        internal static string DatabaseGuideSummary {
            get {
                return ResourceManager.GetString("DatabaseGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Realtime Database.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send users to the right place in your app whether or not it is already installed..
        /// </summary>
        internal static string DynamicLinksDescription {
            get {
                return ResourceManager.GetString("DynamicLinksDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Dynamic Links.
        /// </summary>
        internal static string DynamicLinksGuideSummary {
            get {
                return ResourceManager.GetString("DynamicLinksGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dynamic Links.
        /// </summary>
        internal static string DynamicLinksName {
            get {
                return ResourceManager.GetString("DynamicLinksName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load the UnityEditor.iOS.Extensions.Xcode dll.
        ///Is iOS support installed?.
        /// </summary>
        internal static string FailedToLoadIOSExtensions {
            get {
                return ResourceManager.GetString("FailedToLoadIOSExtensions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Firebase gives you the tools and infrastructure from Google to help you develop, grow and earn money from your app..
        /// </summary>
        internal static string FirebaseDescription {
            get {
                return ResourceManager.GetString("FirebaseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call Cloud Functions directly from your app..
        /// </summary>
        internal static string FunctionsDescription {
            get {
                return ResourceManager.GetString("FunctionsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Cloud Functions for Firebase.
        /// </summary>
        internal static string FunctionsGuideSummary {
            get {
                return ResourceManager.GetString("FunctionsGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloud Functions for Firebase.
        /// </summary>
        internal static string FunctionsName {
            get {
                return ResourceManager.GetString("FunctionsName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No {0} files found in your project so it is not possible to generate Firebase Android resources file {1}.
        ///Building without Firebase Android resources ({1}) will result in an app that will fail to initialize.
        ///
        ///To resolve this problem, follow the setup instructions at {2}.
        /// </summary>
        internal static string GoogleServicesAndroidFileMissing {
            get {
                return ResourceManager.GetString("GoogleServicesAndroidFileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated Firebase Android Resources file {0} from {1}
        ///
        ///Executed {2}.
        /// </summary>
        internal static string GoogleServicesAndroidGenerateXml {
            get {
                return ResourceManager.GetString("GoogleServicesAndroidGenerateXml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generation of the Firebase Android resource file {0} from {1} failed.
        ///If you have not included a valid Firebase Android resources in your app it will fail to initialize.
        ///
        ///{2}
        ///{3}
        ///
        ///You can start to diagnose this issue by executing &quot;{2}&quot; from the command line..
        /// </summary>
        internal static string GoogleServicesAndroidGenerationFailed {
            get {
                return ResourceManager.GetString("GoogleServicesAndroidGenerationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Would you like to change your bundle ID from {0} to {1}?.
        /// </summary>
        internal static string GoogleServicesChangeBundleId {
            get {
                return ResourceManager.GetString("GoogleServicesChangeBundleId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Bundle ID {0} does not match any bundle IDs in your {1} files.
        ///This will result in an app that will fail to initialize.
        ///
        ///Available Bundle IDs:
        ///{2}
        ///
        ///You need to either:
        ///* Fix your app&apos;s bundle ID under &quot;Player Settings --&gt; Bundle Identifier&quot;
        ///or:
        ///* Add another app to your firebase project
        ///  Goto {3}
        ///  and add the new configuration file to your project..
        /// </summary>
        internal static string GoogleServicesFileBundleIdMissing {
            get {
                return ResourceManager.GetString("GoogleServicesFileBundleIdMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple {0} files found in your project. Using {1} (bundle ID {2}) to configure Firebase.
        ///
        ///All files present:
        ///{3}.
        /// </summary>
        internal static string GoogleServicesFileMultipleFiles {
            get {
                return ResourceManager.GetString("GoogleServicesFileMultipleFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No {0} files found in your project.
        ///Building without Firebase configuration will result in an app that will fail to initialize.
        ///
        ///To resolve this problem, follow the setup instructions at {1}.
        /// </summary>
        internal static string GoogleServicesIOSFileMissing {
            get {
                return ResourceManager.GetString("GoogleServicesIOSFileMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect Bundle ID.
        /// </summary>
        internal static string GoogleServicesMismatchedBundleId {
            get {
                return ResourceManager.GetString("GoogleServicesMismatchedBundleId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to find command line tool {0} required for Firebase Android resource generation.
        ///{0} is required to generate the Firebase Android resource file {1} from {2}. Without Firebase Android resources, your app will fail to initialize.
        ///{0} was distributed with each Firebase Unity SDK plugin, was it deleted?
        ///
        ///{3}.
        /// </summary>
        internal static string GoogleServicesToolMissing {
            get {
                return ResourceManager.GetString("GoogleServicesToolMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Let your existing users easily share your app, or their favorite in-app content, via email or SMS..
        /// </summary>
        internal static string InvitesDescription {
            get {
                return ResourceManager.GetString("InvitesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send Firebase invites from your app.
        /// </summary>
        internal static string InvitesGuideSummary {
            get {
                return ResourceManager.GetString("InvitesGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invites and Dynamic Links.
        /// </summary>
        internal static string InvitesName {
            get {
                return ResourceManager.GetString("InvitesName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        internal static string IOS {
            get {
                return ResourceManager.GetString("IOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready to use Firebase on iOS.
        /// </summary>
        internal static string IOSConnected {
            get {
                return ResourceManager.GetString("IOSConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To connect Firebase for iOS, add the GoogleService-Info.plist from Firebase to your Assets..
        /// </summary>
        internal static string IOSDisconnected {
            get {
                return ResourceManager.GetString("IOSDisconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Firebase iOS builds are not supported on Windows. Please build on a OSX machine instead..
        /// </summary>
        internal static string IOSNotSupportedOnWindows {
            get {
                return ResourceManager.GetString("IOSNotSupportedOnWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open in Console.
        /// </summary>
        internal static string OpenConsole {
            get {
                return ResourceManager.GetString("OpenConsole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} file missing {1}, Google Sign-In will fail to initialize.
        ///To resolve this issue follow the instructions at {2}.
        /// </summary>
        internal static string PropertyMissingForGoogleSignIn {
            get {
                return ResourceManager.GetString("PropertyMissingForGoogleSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customize and experiment with app behavior using cloud-based configuration parameters..
        /// </summary>
        internal static string RemoteConfigDescription {
            get {
                return ResourceManager.GetString("RemoteConfigDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Remote Config.
        /// </summary>
        internal static string RemoteConfigGuideSummary {
            get {
                return ResourceManager.GetString("RemoteConfigGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote Config.
        /// </summary>
        internal static string RemoteConfigName {
            get {
                return ResourceManager.GetString("RemoteConfigName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Store files with ease..
        /// </summary>
        internal static string StorageDescription {
            get {
                return ResourceManager.GetString("StorageDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set up Firebase Storage.
        /// </summary>
        internal static string StorageGuideSummary {
            get {
                return ResourceManager.GetString("StorageGuideSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory {0}. Is the directory read-only?.
        /// </summary>
        internal static string UnableToCreateDirectory {
            get {
                return ResourceManager.GetString("UnableToCreateDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Python executable executable {0} failed.
        /// </summary>
        internal static string PythonScriptExecutionFailed {
            get {
                return ResourceManager.GetString("PythonScriptExecutionFailed", resourceCulture);
            }
        }
    }
}
