//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firebase.Editor {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Link {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Link() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firebase.Editor.Link", typeof(Link).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/analytics/.
        /// </summary>
        internal static string AnalyticsGuide {
            get {
                return ResourceManager.GetString("AnalyticsGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/namespace/firebase/analytics.
        /// </summary>
        internal static string AnalyticsReference {
            get {
                return ResourceManager.GetString("AnalyticsReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/unity/setup#add_firebase_to_your_app_1.
        /// </summary>
        internal static string AndroidAddApp {
            get {
                return ResourceManager.GetString("AndroidAddApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/unity/setup#setup_for_android.
        /// </summary>
        internal static string AndroidSetup {
            get {
                return ResourceManager.GetString("AndroidSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/auth/.
        /// </summary>
        internal static string AuthGuide {
            get {
                return ResourceManager.GetString("AuthGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth.
        /// </summary>
        internal static string AuthReference {
            get {
                return ResourceManager.GetString("AuthReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/cloud-messaging/.
        /// </summary>
        internal static string CloudMessagingGuide {
            get {
                return ResourceManager.GetString("CloudMessagingGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-messaging.
        /// </summary>
        internal static string CloudMessagingReference {
            get {
                return ResourceManager.GetString("CloudMessagingReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/crashlytics/.
        /// </summary>
        internal static string CrashlyticsGuide {
            get {
                return ResourceManager.GetString("CrashlyticsGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/namespace/firebase/crashlytics.
        /// </summary>
        internal static string CrashlyticsReference {
            get {
                return ResourceManager.GetString("CrashlyticsReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/database/.
        /// </summary>
        internal static string DatabaseGuide {
            get {
                return ResourceManager.GetString("DatabaseGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/database/firebase-database.
        /// </summary>
        internal static string DatabaseReference {
            get {
                return ResourceManager.GetString("DatabaseReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/dynamic-links/.
        /// </summary>
        internal static string DynamicLinksGuide {
            get {
                return ResourceManager.GetString("DynamicLinksGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/dynamic-links/dynamic-links.
        /// </summary>
        internal static string DynamicLinksReference {
            get {
                return ResourceManager.GetString("DynamicLinksReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/functions/.
        /// </summary>
        internal static string FunctionsGuide {
            get {
                return ResourceManager.GetString("FunctionsGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/functions/firebase-functions.
        /// </summary>
        internal static string FunctionsReference {
            get {
                return ResourceManager.GetString("FunctionsReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/invites/.
        /// </summary>
        internal static string InvitesGuide {
            get {
                return ResourceManager.GetString("InvitesGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/invites/firebase-invites.
        /// </summary>
        internal static string InvitesReference {
            get {
                return ResourceManager.GetString("InvitesReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/unity/setup#add_firebase_to_your_app.
        /// </summary>
        internal static string IOSAddApp {
            get {
                return ResourceManager.GetString("IOSAddApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/unity/setup#setup_for_ios.
        /// </summary>
        internal static string IOSSetup {
            get {
                return ResourceManager.GetString("IOSSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/remote-config/.
        /// </summary>
        internal static string RemoteConfigGuide {
            get {
                return ResourceManager.GetString("RemoteConfigGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/remote-config/firebase-remote-config.
        /// </summary>
        internal static string RemoteConfigReference {
            get {
                return ResourceManager.GetString("RemoteConfigReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/storage/.
        /// </summary>
        internal static string StorageGuide {
            get {
                return ResourceManager.GetString("StorageGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://firebase.google.com/docs/reference/unity/class/firebase/storage/firebase-storage.
        /// </summary>
        internal static string StorageReference {
            get {
                return ResourceManager.GetString("StorageReference", resourceCulture);
            }
        }
    }
}
