name: "ðŸž Bug Report"
description: Please use this template to report issues with the Firebase Unity SDK.
title: '[Bug] '
labels:
  - new
  - 'type: bug'
body:
  - type: markdown
    attributes:
      value: |
        Before getting started, make sure you are in the right place by
        ensuring that filing a bug report is the correct course of
        action for your issue.

        * For general technical questions, post a question on
        [StackOverflow](http://stackoverflow.com/) with the `firebase` tag.

        * For backend, console, and other non-SDK issues, reach out to
        [Firebase Support](https://firebase.google.com/support/) for help.

        If your issue does not fall under the above categories and instead
        involves code in this repository not working as expected, please
        complete and submit this bug report. Thank you!
  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the issue. Explain what you _expected_ to happen and what
        _actually_ happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing the issue
      description: >
        Please provide either **steps to reproduce** or a [**minimal
        reproducible
        example**](https://stackoverflow.com/help/minimal-reproducible-example).

        Providing a minimal reproducible example will help us triage your issue

        faster.
    validations:
      required: false
  - type: input
    attributes:
      label: Firebase Unity SDK Version
      description: What version of the Firebase Unity SDK has this issue?
      placeholder: 11.8.1
    validations:
      required: true
  - type: input
    attributes:
      label: Unity editor version
      description: What version of the Unity editor is being used?
      placeholder: 2022.3.13f1
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation Method
      description: How did you add Firebase to your project?
      options:
        - .unitypackage
        - Unity Package Manager
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Problematic Firebase Component(s)
      description: Which Firebase components are causing issues?
      multiple: true
      options:
        - AB Testing
        - Analytics
        - App Check
        - App Distribution
        - Authentication
        - Crashlytics
        - Database
        - DynamicLinks
        - Firestore
        - Functions
        - In-App Messaging
        - Installations
        - ML Model Downloader
        - Messaging
        - Performance
        - Remote Config
        - Storage
        - All
    validations:
        required: false
  - type: dropdown
    attributes:
      label: Other Firebase Component(s) in use
      description: Which other Firebase components are being used?
      multiple: true
      options:
        - AB Testing
        - Analytics
        - App Check
        - App Distribution
        - Authentication
        - Crashlytics
        - Database
        - DynamicLinks
        - Firestore
        - Functions
        - In-App Messaging
        - Installations
        - ML Model Downloader
        - Messaging
        - Performance
        - Remote Config
        - Storage
        - All
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional SDKs you are using
      description: 'What additional, non-Firebase SDKs are being used?'
      placeholder: 'Facebook, AdMob, etc.'
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Targeted Platform(s)
      description: What platform(s) is the issue affecting?
      multiple: true
      options:
        - Apple Platforms
        - Android
        - Desktop
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Unity editor platform
      description: What platform are you using the Unity editor on?
      multiple: true
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Scripting Runtime
      description: What scripting runtime is being used?
      multiple: true
      options:
        - Mono
        - IL2CPP
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Release Distribution Type
      description: What release distribution is being used?
      multiple: true
      options:
        - 'Pre-built SDK from https://firebase.google.com/download/unity'
        - Open-source from this repo
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output. To enable Firebase debug
        logging, add `-FIRDebugEnabled` to your scheme's launch arguments.
      placeholder: |
        Paste your logs here. Please redact any personally identifiable
        information. This will be automatically formatted into code, so no
        need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'If using CocoaPods for Apple platforms, the project''s Podfile.lock'
      description: The `Podfile.lock` can help us debug versioning issues.
      value: "<!--- Look below for instructions on how to share your Podfile.lock. --->\n\n<details>\n<summary>Expand <code>Podfile.lock</code> snippet</summary>\n<br>\n\n```yml\n\n\U0001F440 Replace this line with the contents of your Podfile.lock!\n\n```\n\n</details>\n"
    validations:
      required: false
