//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firebase.Messaging.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firebase.Messaging.Editor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AutoConfigureAndroid {
            get {
                return ResourceManager.GetString("AutoConfigureAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AutoConfigureAndroidDescription {
            get {
                return ResourceManager.GetString("AutoConfigureAndroidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Configure Xcode for iOS.
        /// </summary>
        internal static string AutoConfigureIOS {
            get {
                return ResourceManager.GetString("AutoConfigureIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Firebase Messaging to auto configure required iOS XCode settings..
        /// </summary>
        internal static string AutoConfigureIOSDescription {
            get {
                return ResourceManager.GetString("AutoConfigureIOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Auto Id.
        /// </summary>
        internal static string DisableAutoId {
            get {
                return ResourceManager.GetString("DisableAutoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables Instance ID autogeneration for messaging services..
        /// </summary>
        internal static string DisableAutoIdDescription {
            get {
                return ResourceManager.GetString("DisableAutoIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Channel Id.
        /// </summary>
        internal static string NotificationChannelId {
            get {
                return ResourceManager.GetString("NotificationChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom channel id for Android notifications.
        /// </summary>
        internal static string NotificationChannelIdDescription {
            get {
                return ResourceManager.GetString("NotificationChannelIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Color.
        /// </summary>
        internal static string NotificationColor {
            get {
                return ResourceManager.GetString("NotificationColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color used to display Android notifications.
        /// </summary>
        internal static string NotificationColorDescription {
            get {
                return ResourceManager.GetString("NotificationColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Icon.
        /// </summary>
        internal static string NotificationIcon {
            get {
                return ResourceManager.GetString("NotificationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set icon used to display Android notifications.
        /// </summary>
        internal static string NotificationIconDescription {
            get {
                return ResourceManager.GetString("NotificationIconDescription", resourceCulture);
            }
        }
    }
}
