//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firebase.Analytics.Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firebase.Analytics.Editor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics Collection.
        /// </summary>
        internal static string AnalyticsCollection {
            get {
                return ResourceManager.GetString("AnalyticsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Configure Android.
        /// </summary>
        internal static string AutoConfigureAndroid {
            get {
                return ResourceManager.GetString("AutoConfigureAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Firebase Analytics to auto configure required Android settings..
        /// </summary>
        internal static string AutoConfigureAndroidDescription {
            get {
                return ResourceManager.GetString("AutoConfigureAndroidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Configure XCode.
        /// </summary>
        internal static string AutoConfigureIOS {
            get {
                return ResourceManager.GetString("AutoConfigureIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Firebase Analytics to auto configure required iOS XCode settings..
        /// </summary>
        internal static string AutoConfigureIOSDescription {
            get {
                return ResourceManager.GetString("AutoConfigureIOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Personal Ads.
        /// </summary>
        internal static string DisablePersonalAds {
            get {
                return ResourceManager.GetString("DisablePersonalAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable using user&apos;s future Analytics data for personalized advertising..
        /// </summary>
        internal static string DisablePersonalAdsDescription {
            get {
                return ResourceManager.GetString("DisablePersonalAdsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string OptionEnabled {
            get {
                return ResourceManager.GetString("OptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently Disabled.
        /// </summary>
        internal static string OptionPermanetlyDisabled {
            get {
                return ResourceManager.GetString("OptionPermanetlyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Disabled.
        /// </summary>
        internal static string OptionTemporaryDisabled {
            get {
                return ResourceManager.GetString("OptionTemporaryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Advert Id.
        /// </summary>
        internal static string PermanentlyDisableAndroidADID {
            get {
                return ResourceManager.GetString("PermanentlyDisableAndroidADID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable collection of ADID (Advertising Identifier)..
        /// </summary>
        internal static string PermanentlyDisableAndroidADIDDescription {
            get {
                return ResourceManager.GetString("PermanentlyDisableAndroidADIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Vendor Id.
        /// </summary>
        internal static string PermanentlyDisableAndroidSSAID {
            get {
                return ResourceManager.GetString("PermanentlyDisableAndroidSSAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable collection of SSAID (Secure Android Identifier)..
        /// </summary>
        internal static string PermanentlyDisableAndroidSSAIDDescription {
            get {
                return ResourceManager.GetString("PermanentlyDisableAndroidSSAIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Advert Id.
        /// </summary>
        internal static string PermanentlyDisableAppleIDFA {
            get {
                return ResourceManager.GetString("PermanentlyDisableAppleIDFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable collection of IDFA (Advertising Identifier)..
        /// </summary>
        internal static string PermanentlyDisableAppleIDFADescription {
            get {
                return ResourceManager.GetString("PermanentlyDisableAppleIDFADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Vendor Id.
        /// </summary>
        internal static string PermanentlyDisableAppleIDFV {
            get {
                return ResourceManager.GetString("PermanentlyDisableAppleIDFV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable collection of IDFV (Identifier for Vendor)..
        /// </summary>
        internal static string PermanentlyDisableAppleIDFVDescription {
            get {
                return ResourceManager.GetString("PermanentlyDisableAppleIDFVDescription", resourceCulture);
            }
        }
    }
}
