// Copyright 2017 Google Inc. All Rights Reserved.
using System;

namespace Firebase
{
  // This class is intended only for tests to be run directly using mono.
  // API changes can be made directly to this class or if there are too many, this class
  // can be regenerated by running a decompiler (say resharper) on Firebase.App.dll in the unity package.
  // The decompiled code will have to be massaged quite a bit and all p/invokes removed, so this route
  // may take a lot longer than simple hand edits.
  public sealed class AppOptions : IDisposable
  {
    public Uri DatabaseUrl
    {
      get;set;
    }

    public string AppId
    {
      get; set;
    }

    public string ApiKey
    {
      get; set;
    }

    public string MessageSenderId
    {
      get; set;
    }

    public string GoogleAnalyticsTrackingId
    {
      get; set;
    }

    public string StorageBucket
    {
      get; set;
    }

    ~AppOptions()
    {
      Dispose();
    }

    public void Dispose()
    {
      lock (this as object)
      {
        GC.SuppressFinalize(this);
      }
    }
  }
}
