# Workflow to handle building the Unity SDK on windows
name: Build windows Reuse

on:
  workflow_call:
    inputs:
      unity_version:
        description: 'Unity version'
        default: '2019'
        required: true
        type: string
      firebase_cpp_sdk_version:
        description: 'Firebase CPP SDK version to build against (The branch, tag or SHA to checkout)'
        default: ''
        required: false
        type: string
      unity_branch:
        description: 'Unity branch to build against, empty means current branch'
        default: ''
        type: string
      apis:
        description: 'CSV of apis to build and test'
        default: 'analytics,auth,crashlytics,database,dynamic_links,firestore,functions,installations,messaging,remote_config,storage'
        required: true
        type: string
      unity_platform_name:
        description: 'The platform name Unity should install with'
        default: ''
        required: true
        type: string
      # Additional CMake flags to use
      additional_cmake_flags:
        description: 'Additional flags to pass into CMake'
        default: ''
        required: false
        type: string

jobs:
  build_desktop:
    name: build-windows-unity${{inputs.unity_version}}-CPP${{ inputs.firebase_cpp_sdk_version }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
    
    env:
        # LC_ALL, LANG and U3D_PASSWORD are needed for U3D.
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
        U3D_PASSWORD: ""
        # Disable checking for U3D updates, since it is buggy
        U3D_SKIP_UPDATE_CHECK: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: ${{ inputs.unity_branch }}

      - uses: actions/checkout@v2
        with:
          repository: firebase/firebase-cpp-sdk
          path: firebase-cpp-sdk
          submodules: true
          ref: ${{ inputs.firebase_cpp_sdk_version }}

      - name: Support longpaths
        run: git config --system core.longpaths true

      # Set up the requirements, and install Unity
      # Ruby setup has to happen before python install and setup, to keep the absl config.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Install Unity installer (U3D)
        shell: bash
        run: gem install u3d -v 1.2.3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Add msbuild to PATH (windows)
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install prerequisites
        shell: bash
        run: |
          echo "FIREBASE_CPP_SDK_DIR=${{ github.workspace }}/firebase-cpp-sdk" >> $GITHUB_ENV
          cd firebase-cpp-sdk
          python scripts/gha/install_prereqs_desktop.py
          cd ..

      - name: Install python deps
        shell: bash
        run: |
          pip install -r scripts/gha/requirements.txt

      - name: Install OpenSSL (Windows)
        run: |
          choco install openssl -r

      - name: Install Unity
        shell: bash
        run: |
          python scripts/gha/unity_installer.py --install --platforms ${{ inputs.unity_platform_name }} --version ${{ inputs.unity_version }}

      - name: Setup Unity path
        shell: bash
        run: |
          echo "UNITY_ROOT_DIR=$( python scripts/gha/print_matrix_configuration.py -u ${{inputs.unity_version}} -k unity_path )" >> $GITHUB_ENV
          echo "$(swig -swiglib)" >> $GITHUB_PATH
          swig -swiglib
          echo "SWIG_DIR=$(swig -swiglib)" >> $GITHUB_ENV
      
      - name: Build SDK (Windows)
        shell: bash
        run: |
          # TODO add handling cmake_extras
          python scripts/build_scripts/build_zips.py --platform=windows --unity_root="$UNITY_ROOT_DIR" --swig_dir="$SWIG_DIR" --apis=${{ inputs.apis }}

      - name: Check zip file
        shell: bash
        run: |
          if [ -f windows_unity/*.zip ]; then
            echo "windows_unity zip created."
          else
            echo "Fail to create windows_unity zip."
            exit 1
          fi

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: windows_unity
          path: windows_unity/*.zip
