# Workflow to handle building the Unity SDK on android
name: Build Android (SubWorkflow)

on:
  workflow_call:
    inputs:
      unity_version:
        description: 'Unity version'
        default: '2019'
        required: true
        type: string
      firebase_cpp_sdk_version:
        description: 'Firebase CPP SDK version to build against (The branch, tag or SHA to checkout)'
        default: ''
        required: false
        type: string
      unity_branch:
        description: 'Unity branch to build against, empty means current branch'
        default: ''
        type: string
      apis:
        description: 'CSV of apis to build and test'
        default: 'analytics,app_check,auth,crashlytics,database,dynamic_links,firestore,functions,installations,messaging,remote_config,storage'
        required: true
        type: string
      unity_platform_name:
        description: 'The platform name Unity should install with'
        default: ''
        required: true
        type: string
      # Additional CMake flags to use
      additional_cmake_flags:
        description: 'Additional flags to pass into CMake'
        default: ''
        required: false
        type: string

jobs:
  build_android:
    name: build-android-unity${{ inputs.unity_version }}-CPP${{ inputs.firebase_cpp_sdk_version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
    env:
      CCACHE_DIR: ${{ github.workspace }}/ccache_dir
  
    steps:
      - name: Checkout Unity Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ inputs.unity_branch }}
          fetch-depth: 0
          
      - name: Checkout CPP Repo
        uses: actions/checkout@v3
        with:
          repository: firebase/firebase-cpp-sdk
          path: firebase-cpp-sdk
          ref: ${{ inputs.firebase_cpp_sdk_version }}
          submodules: true
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache NDK
        id: cache_ndk
        uses: actions/cache@v3
        with:
          path: /tmp/android-ndk-r21e
          key: android-ndk-${{ matrix.os }}-r21e

      - name: Check cached NDK
        shell: bash
        if: steps.cache_ndk.outputs.cache-hit != 'true'
        run: |
          # If the NDK failed to download from the cache, but there is a
          # /tmp/android-ndk-r21e directory, it's incomplete, so remove it.
          if [[ -d "/tmp/android-ndk-r21e" ]]; then
            echo "Removing incomplete download of NDK"
            rm -rf /tmp/android-ndk-r21e
          fi

      - name: Install prerequisites
        shell: bash
        run: |
          echo "FIREBASE_CPP_SDK_DIR=${{ github.workspace }}/firebase-cpp-sdk" >> $GITHUB_ENV
          cd firebase-cpp-sdk
          python scripts/gha/install_prereqs_desktop.py
          build_scripts/android/install_prereqs.sh
          cd ..
          echo "NDK_ROOT=/tmp/android-ndk-r21e" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/tmp/android-ndk-r21e" >> $GITHUB_ENV

      - name: Install python deps
        shell: bash
        run: |
          pip install -r scripts/gha/requirements.txt
      
      - id: unity_setup
        uses: ./gha/unity
        timeout-minutes: 30
        with:
          version: ${{ inputs.unity_version }}
          platforms: ${{ inputs.unity_platform_name }}

      - name: Display Swig Version
        shell: bash
        run: |
          swig -version

      - name: Build SDK (Android)
        timeout-minutes: 90
        shell: bash
        run: |
          # TODO add handling cmake_extras
          python scripts/build_scripts/build_zips.py --gha --platform=android --unity_root=$UNITY_ROOT_DIR --apis=${{ inputs.apis }}

      - name: Check zip file
        shell: bash
        run: |
          if [ -f android_unity/*.zip ]; then
            echo "android_unity zip created."
          else
            echo "Fail to create android_unity zip."
            exit 1
          fi

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: android_unity
          path: android_unity/*.zip
